#!/usr/bin/env bash
# Redirection
ssh ubuntu@104.196.146.115 -i ~/.ssh/holberton 'new="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=TDMfk76hMSQ permanent;"'
ssh ubuntu@104.196.146.115 -i ~/.ssh/holberton 'sudo sed -i "26i\ $new" /etc/nginx/sites-available/default'
