#!/usr/bin/env bash
# Redirection
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo chmod 777 /etc/nginx/sites-enabled/default
sudo sed -i "/# Note: You should disable gzip for SSL traffic./a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
