#!/usr/bin/env bash
# Install a load balance
sudo apt show haproxy
sudo add-apt-repository -y ppa:vbernat/haproxy-1.7
sudo apt update
sudo apt install -y haproxy
sudo chmod 777 /etc/haproxy/haproxy.cfg
sudo echo -e "frontend http_front
   bind *:80
   stats uri /haproxy?stats
   default_backend http_back

backend http_back
   balance roundrobin
   server 1128-web-01 104.196.146.115:80 check
   server 1128-web-02 18.215.147.155:80 check" | tee -a /etc/haproxy/haproxy.cfg
sudo systemctl restart haproxy
