#!/usr/bin/env bash
# Nginx likes port 80
sudo rm /etc/nginx/sites-enabled/default
ln -s /etc/sites-available/default  /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo service nginx reload
