#!/usr/bin/env bash
# gives information about the holbertonschool file
x=1

while [ $x -lt 101 ]
do
mod3=$x%3
mod5=$x%5
if [[ $mod3 -eq "0" ]] && [[ $mod5 -eq "0" ]]; then
	echo "FizzBuzz"
elif [[ $mod5 -eq "0" ]]; then
	echo "Buzz"
elif [[ $mod3 -eq "0" ]]; then
	echo "Fizz"
else
	echo "$x"
fi
x=$((x+1))
done
