#!/usr/bin/env bash
# gives information about the holbertonschool file
x=1
while [ $x -lt 101 ]
do
if [[ $x%3 -eq 0 ]] && [[ $x%5 -eq 0 ]]; then
	echo "FizzBuzz"
elif [[ $x%5 -eq 0 ]]; then
	echo "Buzz"
elif [[ $x%3 -eq 0 ]]; then
	echo "Fizz"
else
	echo "$x"
fi
x=$((x+1))
done
