#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
h=0
m=0
while [ $m -lt 60 ]
do
	if [ $m -eq 59 ]; then
		m=0
	fi
	m=$((m+1))
        if [ $m -eq 1 ]; then
                if [ $h -eq 12 ]; then
                        h=-1
                fi
        	h=$((h+1))
                echo "Hour: $h"
	fi
        echo $m
done
