#!/usr/bin/env bash
# gives information about the holbertonschool file
x=holbertonschool
if [[ -f "$x" ]] || [[ -d "$x" ]]; then
	echo "$x file exists"
	echo "$x is a regular file"
	if [ -s $x ]; then
    		echo "$x file is not empty"
	else
		echo "$x file is empty"
	fi
else
	echo "$x file does not exist"
fi
